server:
  port: 8081
  servlet:
    context-path: /api/v1
spring:
  main:
    banner-mode: console
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    username: root
    password: Bk454454.
    url: jdbc:mysql://localhost:3306/springDB
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true



logging:
  level:
    root: info
